# Generated by Django 3.0.5 on 2021-01-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='allow_explicit',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
