# Generated by Django 3.0.5 on 2020-12-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspage',
            name='username',
            field=models.CharField(default='', max_length=9223372036854775807, unique=True),
        ),
    ]
