# Generated by Django 3.1.5 on 2021-01-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=1000, unique=True)),
                ('playlist_dest', models.CharField(default='', max_length=1000, unique=True)),
                ('auto_siphon', models.BooleanField(default=True, null=True)),
                ('allow_explicit', models.BooleanField(default=False)),
                ('disconnect_account', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
