# Generated by Django 3.1.5 on 2021-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_userpage_last_siphoned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='last_siphoned',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
