# Generated by Django 3.1.5 on 2021-02-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210208_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='last_siphoned',
        ),
    ]
