# Generated by Django 3.1.5 on 2021-02-16 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_userpage_last_siphoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='last_siphoned',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 0, 39, 35, 52638)),
        ),
    ]
