# Generated by Django 3.0.5 on 2020-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siphon', models.BooleanField(default=False)),
                ('automatic_siphon_weekly', models.BooleanField(default=False)),
                ('playlist_destination', models.CharField(default='', max_length=9223372036854775807, unique=True)),
                ('gather_explicit', models.BooleanField(default=True, null=True)),
                ('disonnect_spotify', models.BooleanField(default=False)),
                ('gathered_as_of', models.DateField(auto_now_add=True)),
                ('list_change', models.BooleanField(default=False)),
            ],
        ),
    ]
